export const SET_DANH_SACH_PHIM = "SET_DANH_SACH_PHIM";
export const SET_DANH_SACH_PHIM_PHAN_TRANG = "SET_DANH_SACH_PHIM_PHAN_TRANG";
export const SET_CHI_TIET_PHIM = "SET_CHI_TIET_PHIM";
export const ADMIN_SET_CHI_TIET_PHIM = "ADMIN_SET_CHI_TIET_PHIM";
